// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"EthTest/demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/account/info/:ethAddr",
				Handler: AccountInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/erc20/transfer",
				Handler: ERC20TransferHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/erc20/transfer/info",
				Handler: ERC20TransferInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/eth/block/info",
				Handler: BlockInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/eth/trade",
				Handler: EthTradeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/eth/trade/info",
				Handler: EthTradeInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: DemoHandler(serverCtx),
			},
		},
	)
}
