// Code generated by goctl. DO NOT EDIT.
package types

type AccountRequest struct {
	EthAddr string `path:"ethAddr"`
}

type BlockInfoRequest struct {
	BlockId int64 `form:"block_id"`
}

type DemoRequest struct {
	Name string `path:"name,options=you|me"`
}

type ERC20TransferInfoRequest struct {
	ContractAddress string `form:"contractAddress"`
	StartBlock      int64  `form:"startBlock"`
	EndBlock        int64  `form:"endBlock"`
}

type ERC20TransferRequest struct {
	ToAddress       string `json:"ethAddress"`
	Amount          int64  `json:"amount"`
	ContractAddress string `json:"contractAddress"`
	PrivateKey      string `json:"privateKey"`
	ContractCode    string `json:"contractCode"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type TradeInfoRequest struct {
	TxHash string `form:"tx_hash"`
}

type TradeRequest struct {
	SourceAddr string `json:"sourceAddr"`
	TargetAddr string `json:"targetAddr"`
	Amount     int64  `json:"amount"`
	Price      int    `json:"price"`
	PrivateKey string `json:"privateKey"`
}
